### ISSUE TITLE
Feature request: Add predicates

### ISSUE THREAD

**Issue by Matty9191** [ajor/bpftrace#19]
Want to start by thanking you for your work on bpftrace! This project has a TON of potential and I've had a blast working with it so far. Do you have plans to support predicates similar to DTrace? If not, would it be possible to add these in the future to allow us to limit what we trace? Awesome work!

**Comment by ajor** [comment]
Glad to hear it!

bpftrace does support predicates at the moment, e.g.:
`kprobe:sys_open / comm == "bash" /
{
    printf("%s\n", str(arg0));
}`

Was that what you meant, or is there another DTrace feature that's missing? I should probably add a section on predicates to the readme anyway.

**Comment by Matty9191** [comment]
That's exactly what I was after. I must have missed that in the documentation.  Would you mind if I sent you a PR with a few more examples?

**Comment by ajor** [comment]
Please do!
