### ISSUE TITLE
Why use "-static" option during link stage?

### ISSUE THREAD

**Issue by NanXiao** [ajor/bpftrace#2]
Is there any special meaning for following line in [src/CMakeLists.txt](https://github.com/ajor/bpftrace/blob/5a73475e78e4fb9fcba17f17df76683ecea63331/src/CMakeLists.txt#L6):  

     set(CMAKE_EXE_LINKER_FLAGS "-static")

`Arch Linux` seems don't provide static library for `ncurses`, and this link option will cause link error. Plz refer this [discussion](https://stackoverflow.com/questions/45364104/why-cant-ld-find-libcurses-so-even-though-it-is-in-usr-lib-directory), thanks very much in advance!

**Comment by ajor** [comment]
I wanted bpftrace to be statically linked by default to make it easier to deploy to other machines (just have to copy the single executable), but I've added in an option to support dynamic linking for situations like this where static linking isn't possible. The CMake command now becomes:

`cmake -DDYNAMIC_LINKING:BOOL=ON -DCMAKE_BUILD_TYPE=Release ../`

**Comment by ajor** [comment]
Oh forgot to say that there also seem to be other problems running bpftrace on Arch Linux as it uses LLVM 4.0 (issue #4), so unfortunately it probably still won't work at the moment :(
