### ISSUE TITLE
Switch to Apache 2 licence

### ISSUE THREAD

**Issue by ajor** [ajor/bpftrace#47]
I'd like to switch bpftrace from the MIT licence to Apache 2.0, mainly for the patent-related protections it provides, so that we won't have to worry when merging in patches in the future.

@brendangregg @xbe: As the other contributors to bpftrace, are you ok for your work to be re-licensed under Apache 2.0?

**Comment by brendangregg** [comment]
Yes, switching to Apache 2.0 is fine by me. Thanks.

**Comment by xbe** [comment]
:thumbsup:
