### ISSUE TITLE
Could not resolve symbol: /proc/self/exe:BEGIN_trigger on RHEL7

### ISSUE THREAD

**Issue by mircea-vutcovici** [ajor/bpftrace#50]
OS: RHEL 7
Kernel: 3.10.0-1118.el7.x86_64
bpftrace installed from: https://repos.baslab.org/bpftools/
bpftrace version: bpftrace-0.9.3-1.46e62c0.el7.x86_64

```
[root@rhospbl-3 ~]# /usr/bin/bpftrace -e 'BEGIN { printf("hi\n"); }'
Attaching 1 probe...
Could not resolve symbol: /proc/self/exe:BEGIN_trigger
[root@rhospbl-3 ~]#
```

```
[root@rhospbl-3 ~]# bpftrace -e 'BEGIN { printf("hi\n"); }'
Attaching 1 probe...
Could not resolve symbol: /proc/self/exe:BEGIN_trigger
[root@rhospbl-3 ~]# which bpftrace
/usr/bin/bpftrace
[root@rhospbl-3 ~]# 
```

**Comment by ajor** [comment]
Is your bpftrace executable stripped? (does `nm /path/to/bpftrace` say "no symbols"?)
BEGIN and END probes won't work if that's the case.

If it has symbols and you're still getting this error, please open a ticket at https://github.com/iovisor/bpftrace

**Comment by lxyscls** [comment]
@ajor So how to workaround for such things? I use "sudo apt install bpftrace" under an Ubuntu 22.04 server.

**Comment by ajor** [comment]
I came across this issue by chance this week as well - I've just opened an issue on the official bpftrace repository about it: https://github.com/iovisor/bpftrace/issues/2292
