### ISSUE TITLE
Compilation error in src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp

### ISSUE THREAD

**Issue by kloczek** [ajor/bpftrace#6]
[ 25%] Building CXX object src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp: In member function ‘virtual void bpftrace::ast::CodegenLLVM::visit(bpftrace::ast::Probe&)’:
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp:389:17: error: ‘class llvm::Function’ has no member named ‘getArgumentList’; did you mean ‘Arguments’?
   ctx_ = &func->getArgumentList().front();
                 ^~~~~~~~~~~~~~~
                 Arguments
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp: In member function ‘void bpftrace::ast::CodegenLLVM::createLog2Function()’:
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp:593:28: error: ‘class llvm::Function’ has no member named ‘getArgumentList’; did you mean ‘Arguments’?
   Value *arg = &log2_func->getArgumentList().front();
                            ^~~~~~~~~~~~~~~
                            Arguments
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp: In member function ‘void bpftrace::ast::CodegenLLVM::createStrcmpFunction()’:
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp:631:29: error: ‘class llvm::Function’ has no member named ‘getArgumentList’; did you mean ‘Arguments’?
   Value *s1 = &strcmp_func->getArgumentList().front();
                             ^~~~~~~~~~~~~~~
                             Arguments
/home/tkloczko/rpmbuild/BUILD/bpftrace/src/ast/codegen_llvm.cpp:632:29: error: ‘class llvm::Function’ has no member named ‘getArgumentList’; did you mean ‘Arguments’?
   Value *s2 = &strcmp_func->getArgumentList().back();
                             ^~~~~~~~~~~~~~~
                             Arguments
make[2]: *** [src/ast/CMakeFiles/ast.dir/build.make:87: src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:307: src/ast/CMakeFiles/ast.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by ajor** [comment]
It looks like you're building with LLVM 5 here but bpftrace only supports 3.9 at the moment. This is definitely something we want to fix though, as the LLVM version is holding up other bpftrace features too.
Any patches to help with the LLVM upgrade welcome!

**Comment by ajor** [comment]
LLVM 5 now supported: d1fbcb11a4438baf9c5c755d7ed80b93c7d4c6fc
